package application;

import javafx.fxml.FXML;

import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import javafx.scene.input.MouseEvent;

import javafx.scene.input.InputMethodEvent;

public class Ventana1Controller {
	@FXML
	private TextField textfield1;
	@FXML
	private Button button1;
	@FXML
	private TextField textfield11;

	// Event Listener on Button[#button1].onMouseClicked
	@FXML
	public void btn1control(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on TextField[#textfield11].onInputMethodTextChanged
	@FXML
	public void btn1control(InputMethodEvent event) {
		// TODO Autogenerated
	}
}
